apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db-url-secret.yaml
  - helmrelease.yaml
  - repo.yaml
  - pvc.yaml
  - ingress.yaml
  - server-hpa.yaml
  - servers-deployment.yaml
  - machine-learning-deployment.yaml
  - workers-deployment.yaml
  - workers-hpa.yaml
  - service.yaml
  - machine-learning-service.yaml
