apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-servers
  namespace: apps
  labels:
    app: immich
    role: servers
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: immich
      role: servers
  template:
    metadata:
      labels:
        app: immich
        role: servers
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v2.4.1
          env:
            - name: IMMICH_WORKERS_EXCLUDE
              value: "microservices"
            - name: REDIS_HOSTNAME
              value: immich-redis-master
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: immich-db-url
                  key: DB_URL
            - name: IMMICH_IGNORE_MOUNT_CHECK_ERRORS
              value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 2Gi
          ports:
            - containerPort: 2283
          volumeMounts:
            - name: library
              mountPath: /usr/src/app/upload
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: immich-pvc-nfs
